config/routes.rb
Simoom::Application.routes.draw do
  
  get 'weeks/current' => 'weeks#current', :as => :current_week
  resources :weeks
  
  resources :todo_lists, :only => [:index, :show, :update]
  resources :weeks_todo_lists
  
  root :to => 'weeks#current'
  

end

app/models/week.rb
class Week < ActiveRecord::Base
  
  STATE_DONE = 1
  STATE_UNDONE = 0
  
  has_many :week_todo_lists, :dependent => :destroy
  has_many :todo_lists, :through => :week_todo_lists
  
  validates :available_hours, :presence => true
  validates :nr, :uniqueness => true
  
  after_initialize do
    self.nr = Date.today.cweek if self.nr.blank?
  end
  
  def completed_hours
    todo_lists.where(:state => TodoList::STATE_DONE).inject(0) { |total, todo_list| total += todo_list.estimate.to_i }
  end
  
  def planned_hours
    todo_lists.inject(0) { |total, todo_list| total += todo_list.estimate.to_i }
  end
  
  def hours_left
    available_hours - planned_hours
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  
  respond_to :html, :js, :pdf
  
  def index
    @weeks = Week.order('nr DESC')
  end

  def edit
    @week = Week.includes(:todo_lists).find(params[:id])
    @available_projects = Project.active.by_name.select do |project|
      project.todo_lists.exists?
    end
    respond_with(@week)
  end
  
  def update
    week = Week.find(params[:id])
    if week.update_attributes(params[:week])
      respond_to do |format|
        format.html { redirect_to week_path(week) }
        format.js   { render :update }
      end
    else
      render 'edit'
    end
  end

  def show
    @week = Week.find(params[:id])
    respond_with @week do |format|
      format.pdf do
        @document = PdfTemplate::StoryCard.new(@week)
        send_data @document.to_pdf.render, :filename => "Storycards_Week_#{@week.nr}.pdf", :type => 'application/pdf'
      end
    end
  end

  def new
    @week = Week.new
    respond_with @week
  end
  
  def create
    @week = Week.new params[:week]
    if @week.save
      redirect_to week_path(@week)
    else
      render 'new'
    end
  end
  
  def current
    if week = Week.last
      redirect_to week_path(week)
    end
  end
  
  def destroy
    week = Week.find params[:id]
    week.destroy
    redirect_to weeks_path, :notice => 'Week was successfully deleted'
  end
  
end

app/helpers/weeks_helper.rb
module WeeksHelper
  def week_name
    "Woche #{@week.nr}"
  end
end

app/views/weeks/_completed_hours.html.haml
- if @week.completed_hours.to_i >= @week.available_hours.to_i
  .alert-message.success
    %p= "Geschafft! <b>#{@week.completed_hours}h</b> von <b>#{@week.planned_hours}h</b> sind erledigt!".html_safe
- else
  .alert-message.warning
    %p= "Es sind <b>#{@week.completed_hours}h</b> von <b>#{@week.planned_hours}h</b> erledigt. Auf geht's!".html_safe

app/views/weeks/_form.html.haml
.well
  = simple_form_for @week, :html => { :class => 'form-stacked' } do |f|
    %fieldset
      %legend Stunden eingeben
      #planned-hours
        = render 'planned_hours'
      = f.input :nr, :label => 'Wochen-Nummer'
      = f.input :available_hours, :label => 'Verfügbare Stunden'
      = f.submit 'Woche speichern', :class => 'btn primary'

app/views/weeks/_planned_hours.html.haml
- if @week.planned_hours.to_i > @week.available_hours.to_i
  .alert-message.warning.error= "Es sind mehr Stunden eingeplant als verfügbar sind! <b>(#{@week.planned_hours}/#{@week.available_hours}h)</b>".html_safe
- else
  .alert-message.warning.warning= "Es sind <b>#{@week.planned_hours}h</b> von <b>#{@week.available_hours || 0}h</b> eingeplant".html_safe

app/views/weeks/current.html.haml
- content_for :page_title do
  Es gibt noch keine aktuelle Woche, leg doch mal eine an.
= link_to 'Neue Woche anlegen', new_week_path, :class => 'btn primary'

app/views/weeks/edit.html.haml
- content_for :page_title do
  = "Woche #{@week.nr} bearbeiten"

= render 'form'

%hr
%h2 Todo-Listen in dieser Woche
%br
%table#todo-lists
  = render_todo_lists(@week.todo_lists, :edit)

- content_for :sidebar do
  .well
    = simple_form_for :todo_lists, :url => todo_lists_path(:week_id => @week.id), :html => { :class => 'form-stacked' }, :remote => true, :method => :get do |f|
      %fieldset
        %legend Todo-Listen laden
        = f.input :project_id, :collection => @available_projects, :label => 'Projekt auswählen'
        = f.submit 'Todo Listen anzeigen', :class => 'btn primary'
  %table.todo-lists

app/views/weeks/index.html.haml
- content_for :page_title do
  Wochenübersicht

%table
  - @weeks.each do |week|
    %tr
      %td{ :width => 300 }
        %p= "Woche #{week.nr}"
      %td
        = link_to 'Löschen', week_path(week), :method => :delete, :confirm => "Woche ##{week.nr} wirklich löschen?", :class => 'btn small error'
        = link_to 'Bearbeiten', edit_week_path(week), :class => 'btn small primary'

app/views/weeks/new.html.haml
- content_for :page_title do
  Neue Woche anlegen
= render 'form'

app/views/weeks/show.html.haml
- content_for :page_title do
  = week_name

- content_for :sidebar do
  .well
    = link_to 'Woche bearbeiten', edit_week_path(@week), :class => 'btn primary'
    %br
    %br
    - unless @week.done?
      = simple_form_for @week, :remote => true do |f|
        = f.input :done, :as => :hidden, :input_html => { :value => Week::STATE_DONE }
        = f.submit 'Woche abschliessen', :class => 'btn error'
      
    - if @week.todo_lists.present?
      =link_to 'Karten drucken', week_path(@week, :format => :pdf), :class => 'btn success'

= render 'weeks/completed_hours'

%table#todo-lists
  = render_todo_lists(@week.todo_lists, :complete)

app/views/weeks/update.js.haml
$("#week-done").remove()