config/routes.rb
Simoom::Application.routes.draw do
  
  get 'weeks/current' => 'weeks#current', :as => :current_week
  resources :weeks
  
  resources :todo_lists, :only => [:index, :show, :update]
  resources :weeks_todo_lists
  
  root :to => 'weeks#current'
  

end

app/models/basecamp/todo_list.rb
module Basecamp
  class TodoList < Basecamp::Base
    
    
    def extract_attributes
      {
        :basecamp_id => id,
        :name => name,
        :estimate => (description.present? ? description.scan(Basecamp::Importer::ESTIMATE_MATCHER).flatten.first : nil),
        :state => (completed ? ::TodoList::STATE_DONE : ::TodoList::STATE_UNDONE),
        :position => position
      }
    end
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base

  STATE_DONE = 1
  STATE_UNDONE = 0

  belongs_to :project
  has_many :todo_items

  has_many :week_todo_lists
  has_many :weeks, :through => :week_todo_lists

  default_scope order('state ASC')
  scope :by_position, order('position ASC')
  scope :uncomplete, where('state = ?', STATE_UNDONE)

  #
  # Fetch the child items from basecamp
  #
  def fetch_items
    Basecamp::TodoItem.find(:all, :params => { :todo_list_id => basecamp_id, :filter => 'all' })
  end

  #
  # Map the child items from basecamp to local child objects
  #
  def sync(log_level = :info)
    @logger = Basecamp::ImportLogger.new(log_level)
    basecamp_items = fetch_items

    unless basecamp_items.blank?
      @logger.log :debug, "found #{basecamp_items.size} Todo Items for #{name}"
      todo_items << basecamp_items.map do |item|
        item_attributes = {
          :basecamp_id => item.id,
          :name => item.content
        }

        list_item = ::TodoItem.find_or_initialize_by_basecamp_id(item.id, item_attributes)
        list_item.update_attributes(item_attributes) if list_item.persisted?
        list_item
      end
    end
  end

  def assigned_to_week?(week)
    weeks.include? week
  end

  #
  # Marks the corresponding TodoList in Basecamp as complete
  #
  def complete_in_basecamp
    fetch_items.each do |t|
      t.completed = true
      t.save
    end
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController

  respond_to :html, :js

  def index
    @project = Project.find(params[:todo_lists][:project_id]) rescue nil
    @week = Week.find(params[:week_id])

    @todo_lists = @project.present? ? todo_lists_without_week_for_project(@week, @project) : TodoList.all.by_position
    respond_with @todo_lists
  end

  def update
    todo_list = TodoList.find(params[:id])

    if params[:todo_list][:state] == TodoList::STATE_DONE.to_s
      todo_list.complete_in_basecamp
    end

    if todo_list.update_attributes(params[:todo_list])
      @week = Week.find(params[:week_id])
      @todo_lists = @week.todo_lists
    end
  end

private

  def todo_lists_without_week_for_project(week, project)
    project.todo_lists.by_position.uncomplete.reject do |item|
      week.todo_list_ids.include? item.id
    end
  end

end

app/views/todo_lists/_todo_list.html.haml
%tr.todo-list{ :id => "todo-list-#{todo_list.id}"}
  %td.big-num
    = "#{todo_list.estimate}h"
  %td
    .big= todo_list.name
    .dimmed= todo_list.project.name
  - if action == :complete
    %td
      - if todo_list.state.to_i == TodoList::STATE_DONE
        = link_to 'Eröffnen', todo_list_path(todo_list, 'todo_list[state]' => TodoList::STATE_UNDONE, :week_id => @week.id), :remote => true, :method => :put, :class => 'btn primary small'
      - else
        = link_to 'Abschliessen', todo_list_path(todo_list, 'todo_list[state]' => TodoList::STATE_DONE, :week_id => @week.id), :remote => true, :method => :put, :class => 'btn primary small'

  - elsif action == :edit
    %td
      = link_to 'Aus Woche entfernen', weeks_todo_list_path(WeekTodoList.find_by_week_id_and_todo_list_id(@week.id, todo_list.id)), :method => :delete, :remote => true, :class => 'btn error small'

  - else
    %td
      = link_to 'Hinzufügen', weeks_todo_lists_path(:week_id => params[:week_id].presence, :todo_list_id => todo_list.id ), :remote => true, :method => :post, :class => 'btn primary small'

app/views/todo_lists/index.js.haml
$(".todo-lists").html("#{ escape_javascript(render_todo_lists(@todo_lists, :add)) }")

app/views/todo_lists/update.js.haml
$("#todo-lists").html("#{ escape_javascript(render_todo_lists(@todo_lists, :complete)) }")